### ISSUE TITLE
Voronoi fails on selected face.

### ISSUE THREAD

**Issue by artelse** [reox/FreeCAD_macros#7]
Would love to get this to work, but get this error:
```
08:18:34  Traceback (most recent call last):
08:18:34    File "/home/xxx/.local/share/FreeCAD/v1-2/Macro/Voronoi.FCMacro", line 346, in do
08:18:34      voronoi_on_face(n, offset, tol)
08:18:34    File "/home/xxx/.local/share/FreeCAD/v1-2/Macro/Voronoi.FCMacro", line 416, in voronoi_on_face
08:18:34      sketch.Support = (feature, face_name)
08:18:34      ^^^^^^^^^^^^^^
08:18:34  AttributeError: 'Sketcher.SketchObject' object has no attribute 'Support'
```
The object is a simple rectangle in Sketcher and padded in Part Design. The sketch is part of a body object where a face is selected.

**Comment by reox** [comment]
Well... The Macro is 6 years old and FC has evolved since then. You will probably need to use FC ~0.2~ 0.19 to get this to work.

I haven't looked into macro development since then. Perhaps this is an easy fix to just rename it.

**Comment by artelse** [comment]
Found [these](https://forum.freecad.org/viewtopic.php?p=803999#p803999) forum posts with fixes, but also complete macros that also work with FC 1.1.

**Comment by reox** [comment]
I guess there were only two things to change regarding the Attacher. Can you check if it works now with the latest version? For me it does (at leats on a flat face...)

<img width="1139" height="798" alt="Image" src="https://github.com/user-attachments/assets/6752874a-b32f-4f6c-9242-733a3340be2c" />

**Comment by artelse** [comment]
Yes, it works with the misspelled one: `Random_Patern_Voronoi.FCMacro`. Would be great to add to the Add-on manager repo. Have you perhaps made a Penrose tiler as well, haven't seen one for FC.

**Comment by reox** [comment]
> Yes, it works with the misspelled one: Random_Patern_Voronoi.FCMacro

which one is that? That's not from me?

> Have you perhaps made a Penrose tiler as well

unfortunately no

**Comment by artelse** [comment]
That's also on the forum and based upon yours.

[Random_Patern_Voronoi.zip](https://github.com/user-attachments/files/26961060/Random_Patern_Voronoi.zip)

**Comment by reox** [comment]
ah that one. I diffed them and both should now work identically. I removed support for older FC fully - I think that is not needed...

**Comment by artelse** [comment]
Care to add to the Add-on repo?

**Comment by reox** [comment]
Not at the moment, no. The macro is not really well tested, not really maintained and has probably more bugs than features 🤣

**Comment by artelse** [comment]
Understand, would just have been nice to see something else than honeycomb vents in FC designs ;)

**Comment by Nonoobybut** [comment]
I really like this Add-on only one question: is there an easy way to increase the distance between the parallel lines and round the corners? I´m using it for 3D-prints and it is a lot of handwork then. Also the sharp angles that occur sometimes are not good for printing.
Thank you in advance
